#!/usr/bin/env python

def init():
    print('init')

def new():
    print('new')

def list():
    print('list')

def config():
    print('config')

def generate():
    print('generate')

def link():
    print('link')

def upgradeRepository():
    print('upgrade')

def help():
    print('help')

if __name__ == "__main__":
    help()